#!/bin/bash

base_path="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
temp_scripts=$base_path/.temp
rm -rf $temp_scripts

mkdir -p $temp_scripts

sed "s~xxxbasepathxxx~$base_path~g" $base_path/scripts/submit_qsub.sh | sed 's~xxxcmdxxx~bash $base_path/scripts/build_tree.sh~g' > $temp_scripts/submit_qsub_temp.sh
qsub $temp_scripts/submit_qsub_temp.sh

