#!/bin/bash

if [ "$#" -ne 2 ]; then
  echo ""
  echo "This script downloads all ncbi genomes from a given genus using a PBS qsub job"
  echo "Provide the base directory of the marker gene phylogeny git clone and the bacterial genus"
  echo ""
  echo "Usage: get_genomes <marker_gene_phylogeny_directory> <bacterial_genus>"
  echo ""
fi

cd $1
./download_genomes $2 all
