#!/bin/bash


no_var_output(){
  echo ""
  echo "This script downloads all ncbi genomes from a given genus"
  echo ""
  echo "Please provide the following variables by running the below commands using your own input:"
  echo ""
  echo "export basedir=<marker_gene_phylogeny_directory>"
  echo "export genus=<bacterial_genus>"
  echo ""
  echo "Once the above variables are set then this script will run correctly..."
  echo ""
}


if [ -z ${basedir+x} ]; then
  no_var_output
elif [ -z ${genus+x} ]; then
  no_var_output
else
  cd $basedir
  ./download_genomes $genus all
fi