#!/usr/bin/env python

import sys, os
from Bio import AlignIO

trimmed = AlignIO.read(sys.argv[1], "fasta")
raw = AlignIO.read(sys.argv[2], "fasta")

outdir = os.path.dirname(sys.argv[1])
outfile = open(os.path.join(outdir, "trimming_report.txt"), 'w')

outfile.write("Length of raw alignment = %d\n" % len(raw[0]))
outfile.write("Length of trimmed alignment = %d\n" % len(trimmed[0]))
outfile.write("Percent bases removed by trimming = %.2f%%\n" % ((len(raw[0])-len(trimmed[0]))/len(raw[0]))*100)
outfile.close()
